-- Tested in PostgreSQL 14.2
-- songs ~500
-- albums	50
-- artists 10
-- orders	450
-- order_lines 600
-- customers 45
-- M = 275

DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;

DROP FUNCTION IF EXISTS song_name_randomizer;

CREATE TABLE customers (
  customer_id INT
    GENERATED ALWAYS AS IDENTITY
, fname       VARCHAR(100)
, sname       VARCHAR(100)
, country     VARCHAR(100)
, PRIMARY KEY (customer_id)
);

CREATE TABLE orders (
  order_id    INT
    GENERATED ALWAYS AS IDENTITY
, order_time  TIMESTAMP
    DEFAULT now()
, status      CHAR(1)
    NOT NULL
    CHECK (status IN ('i', 'p', 's', 'd', 'c', 'h', 'r'))
    -- i = in progress
    -- p = purchased
    -- s = sent
    -- d = delivered
    -- c = cancelled
    -- h = on hold
    -- r = refunded
, customer_id INT
, PRIMARY KEY (order_id)
, FOREIGN KEY (customer_id)
    REFERENCES customers (customer_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE artists (
  artist_id    INT
    GENERATED ALWAYS AS IDENTITY
, name         VARCHAR(255)
, active       BOOL
, founded_year INT
, PRIMARY KEY (artist_id)
);

CREATE TABLE albums (
  album_id     INT
    GENERATED ALWAYS AS IDENTITY
, name         VARCHAR(255)
, release_year INT
, genre        VARCHAR(100)
, available    BOOL
, artist_id    INT
, PRIMARY KEY (album_id)
, FOREIGN KEY (artist_id)
    REFERENCES artists (artist_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE order_lines (
  order_id INT
, album_id INT
, quantity INT
    CHECK (quantity > 0)
, PRIMARY KEY (order_id, album_id)
, FOREIGN KEY (order_id)
    REFERENCES orders (order_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
, FOREIGN KEY (album_id)
    REFERENCES albums (album_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE songs (
  song_id    INT
    GENERATED ALWAYS AS IDENTITY
, name       VARCHAR(255)
, position   INT
, length_sec INT
, album_id   INT
, artist_id  INT -- featured artist
, PRIMARY KEY (song_id)
, FOREIGN KEY (album_id)
    REFERENCES albums (album_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
, FOREIGN KEY (artist_id)
    REFERENCES artists (artist_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

-- Restart identities just in case:
TRUNCATE TABLE customers   RESTART IDENTITY CASCADE;
TRUNCATE TABLE orders      RESTART IDENTITY CASCADE;
TRUNCATE TABLE order_lines RESTART IDENTITY CASCADE;
TRUNCATE TABLE albums      RESTART IDENTITY CASCADE;
TRUNCATE TABLE artists     RESTART IDENTITY CASCADE;
TRUNCATE TABLE songs       RESTART IDENTITY CASCADE;

-- Data for customers:
WITH fnames AS (
  SELECT fname
  FROM   (VALUES 
    (NULL)
  , ('Rene')
  , ('Vince')
  , ('Opal')
  , ('Keefe')
  , ('Heath')
  , ('Corbin')
  , ('Patrick')
  , ('Elva Jocelyn')
  , ('Jesselyn')
  , ('Guillema')
  , ('Harley')
  , ('Tris')
  , ('Norry')
  , ('Ahmed')
  , ('Sarajane')
  , ('Adelaide')
  , ('Janina')
  , ('Clemmie')
  , ('Bess')
  , ('Anthea')
  , ('Jamie')
  , ('Jehu')
  , ('Gayla')
  , ('Brenda')
  , ('Suki')
  , ('Brina')
  , ('Dulcia')
  , ('Harry')
  , ('Bobina')
  , ('Hartley')
  , ('Zeke')
  , ('Scott Francis')
  , ('Wayland')
  , ('Kimberley')
  , ('Lotta')
  , ('Lynn')
  , ('Gregor')
  , ('Ag')
  , ('Constantine')
  , ('Porter')
  , ('Hyacinthie')
  , ('Dill')
  , ('Quincey')
  , ('Felix')
  , ('Wini')
  , ('Jake')
  , ('Audrey')
  , ('Sigismund')
  , ('Daniella')
  ) AS t (fname)
)
,    snames AS (
  SELECT sname
  FROM   (VALUES 
    (NULL)
  , ('Gallard')
  , ('Isakowicz')
  , ('Iacoboni')
  , ('McDunlevy')
  , ('Lammas')
  , ('Deathridge')
  , ('Crayden')
  , ('Xi')
  , ('Mehmet')
  , ('Jeandillou')
  , ('Byrne')
  , ('Jaquest')
  , ('Aleksankov')
  , ('Drummond')
  , ('Arrighetti')
  , ('Duckham')
  , ('Tallett')
  , ('Van Daalen')
  , ('Semper')
  , ('O''Malley')
  , ('Donner')
  , ('Shea')
  , ('Wahlgren')
  , ('Bough')
  , ('Giraux')
  , ('Keig')
  , ('Fielders')
  , ('Osburn')
  , ('McMenamie')
  ) AS t (sname)
)
,    countries AS (
  SELECT country
  FROM   (VALUES
    (NULL)
  , ('United States')
  , ('England')
  , ('Ireland')
  , ('China')
  , ('Finland')
  , ('France')
  , ('Indonesia')
  , ('India')
  , ('Netherlands')
  ) AS t (country)
)
INSERT INTO customers (fname, sname, country) 
  SELECT fnames.fname
        , snames.sname
        , countries.country
  FROM    fnames
        , snames
        , countries
  ORDER BY random()
  LIMIT 45;

-- Data for orders:
WITH customer_ids AS (
  SELECT customer_id 
  FROM   customers
  WHERE  customer_id <>
    (SELECT AVG(customer_id)
    FROM customers)
)
,    status_codes AS (
  SELECT status
  FROM (VALUES
    ('i')
  , ('p')
  , ('s')
  , ('d')
  , ('c')
  , ('h')
  , ('r')
  ) AS t (status)
)
,    times AS (
  SELECT now()::timestamp +
          random() * (now()::timestamp -
                      now()::timestamp - INTERVAL '5 years') AS times
        , generate_series(1, 1000)
)
INSERT INTO orders (order_time, status, customer_id)
  SELECT times.times
        , status_codes.status
        , customers.customer_id
  FROM    customers
        , status_codes
        , times
  ORDER BY random()
  LIMIT 450;

DELETE FROM orders
WHERE customer_id = ROUND((random()::decimal + 1) * 10)::integer;

-- Data for artists:
WITH artist_names AS (
  SELECT name
  FROM   (VALUES
  ('.38 Special')
, ('10cc')
, ('3 Doors Down')
, ('4 Non Blondes')
, ('a-ha')
, ('AC/DC')
, ('Ace')
, ('Adelitas Way')
, ('Aerosmith')
, ('Alanis Morissette')
, ('Alannah Myles')
, ('Aldo Nova')
, ('Alice Cooper')
, ('Alice In Chains')
, ('Allman Brothers Band')
, ('America')
, ('Animals II')
, ('Ann Wilson')
, ('April Wine')
, ('Argent')
, ('Arlo Guthrie')
, ('Artful Dodger')
, ('Asia')
, ('Atlanta Rhythm Section')
, ('Audioslave')
, ('Autograph')
, ('Axe')
, ('Bachman-Turner Overdrive')
, ('Bad Company')
, ('Bad English')
, ('Badfinger')
, ('Baton Rouge')
, ('Beastie Boys')
, ('Beck')
, ('Big Country')
, ('Bill Haley')
, ('Bill Withers')
, ('Billy Idol')
, ('Billy Joel')
, ('Billy Rankin')
, ('Billy Squier')
, ('Billy Thorpe')
, ('Black Sabbath')
, ('Blackfoot')
, ('Blind Faith')
, ('Blind Melon')
, ('Blink-182')
, ('Blondie')
, ('Blue Oyster Cult')
, ('Blur')
, ('Bob Dylan')
, ('Bob Marley')
, ('Bob Seger')
, ('Bob Welch')
, ('Bon Jovi')
, ('Bonham')
, ('Booker T. and the MG''s')
, ('Boston')
, ('Boz Scaggs')
, ('Brewer & Shipley')
, ('Bruce Hornsby & The Range')
, ('Bruce Springsteen')
, ('Bryan Adams')
, ('Buckcherry')
, ('Buffalo Springfield')
, ('Bush')
, ('Candlebox')
, ('Canned Heat')
, ('Carole King')
, ('Cat Stevens')
, ('Charlie Daniels Band')
, ('Cheap Trick')
, ('Chevelle')
, ('Chicago')
, ('Chuck Berry')
, ('Cinderella')
, ('Clarks')
, ('Collective Soul')
, ('Commander Cody')
, ('Coney Hatch')
, ('Counting Crows')
, ('Cracker')
, ('Cream')
, ('Creed')
, ('Creedence Clearwater Revival')
, ('Crosby, Stills & Nash')
, ('Crosby, Stills, Nash & Young')
, ('Cutting Crew')
, ('Damn Yankees')
, ('Dave Edmunds')
, ('Dave Mason')
, ('David & David')
, ('David Bowie')
, ('David Essex')
, ('David Gilmour')
, ('David Johansen')
, ('David Lee Roth')
, ('Deep Purple')
, ('Def Leppard')
, ('Depeche Mode')
, ('Derek & The Dominos')
, ('Detective')
, ('Dick Siegel')
, ('Dio')
, ('Dire Straits')
, ('Dishwalla')
, ('Dobie Gray')
, ('Dokken')
, ('Don Felder')
, ('Don Henley')
, ('Don McLean')
, ('Donnie Iris')
, ('Donovan')
, ('Dr. Hook & the Medicine Show')
, ('Dr. John')
, ('Dramarama')
, ('Led Zeppelin')
, ('Duran Duran')
, ('Eagles')
, ('Eddie Money')
, ('Edgar Winter Group')
, ('Edwin Starr')
, ('Electric Light Orchestra')
, ('Elton John')
, ('Elvin Bishop')
, ('Elvis Costello')
, ('Emerson, Lake & Palmer')
, ('Eric Clapton')
, ('Eric Johnson')
, ('Europe')
, ('Eurythmics')
, ('Eve 6')
, ('Everclear')
, ('Everlast')
, ('Extreme')
, ('Faces')
, ('Faith No More')
, ('Faster Pussycat')
, ('Firm')
, ('Five Man Electrical Band')
, ('Fleetwood Mac')
, ('Focus')
, ('Foghat')
, ('Foo Fighters')
, ('Foreigner')
, ('Frank Zappa')
, ('Free')
, ('Funkadelic')
, ('Gary Numan')
, ('Gary Wright')
, ('Genesis')
, ('George Harrison')
, ('George Thorogood')
, ('Georgia Satellites')
, ('Gerry Rafferty')
, ('Gin Blossoms')
, ('Glenn Frey')
, ('Gold Star Ballroom Orchestra')
, ('Golden Earring')
, ('Gordon Lightfoot')
, ('Gov''t Mule')
, ('Grand Funk Railroad')
, ('Grateful Dead')
, ('Great White')
, ('Green Day')
, ('Greg Kihn Band')
, ('Gregg Allman')
, ('Guess Who')
, ('Guns N'' Roses')
, ('Gypsy')
, ('Harold Faltermeyer')
, ('Harry Chapin')
, ('Harry Nilsson')
, ('Head East')
, ('Heart')
, ('Heartsfield')
, ('HellYeah')
, ('Henry Paul Band')
, ('Hollies')
, ('Honeymoon Suite')
, ('Hooters')
, ('Huey Lewis & The News')
, ('Humble Pie')
, ('Iggy Pop')
, ('Imagine Dragons')
, ('INXS')
, ('Iron Butterfly')
, ('Iron Maiden')
, ('J. Geils Band')
, ('Jackson Browne')
, ('James Gang')
, ('JAMES TAYLOR')
, ('Jane''s Addiction')
, ('Janis Joplin')
, ('Jay Ferguson')
, ('Jeff Beck')
, ('Jefferson Airplane')
, ('Jefferson Starship')
, ('Jesus Jones')
, ('Jet')
, ('Jethro Tull')
, ('Jim Croce')
, ('Jimi Hendrix')
, ('Jimmy Buffett')
, ('Joan Jett')
, ('Joe Cocker')
, ('Joe Jackson')
, ('Joe Satriani')
, ('Joe Walsh')
, ('John Cafferty')
, ('John Fogerty')
, ('John Lennon')
, ('John Mellencamp')
, ('John Prine')
, ('Johnny Nash')
, ('Johnny Van Zant')
, ('Jonathan Edwards')
, ('Jonathan Richman')
, ('Journey')
, ('Judas Priest')
, ('Junkyard')
, ('Kansas')
, ('Kenny Loggins')
, ('Kenny Wayne Shepherd')
, ('Kid Rock')
, ('Kingofthehill')
, ('Kings of Leon')
, ('Kiss')
, ('Krokus')
, ('L.A. Guns')
, ('Lake')
, ('Lee Michaels')
, ('Legs Diamond')
, ('Lenny Kravitz')
, ('Leon Russell')
, ('Lit')
, ('Lita Ford')
, ('Little Feat')
, ('Live')
, ('Living Colour')
, ('Local H')
, ('London Symphony Orchestra')
, ('Lou Gramm')
, ('Lou Reed')
, ('Loverboy')
, ('Lynch Mob')
, ('Lynyrd Skynyrd')
, ('Mama''s Pride')
, ('Manfred Mann')
, ('Marcy Playground')
, ('Meat Loaf')
, ('Melissa Etheridge')
, ('Men At Work')
, ('Metallica')
, ('Michael Nesmith')
, ('Michael Stanley')
, ('Midnight Oil')
, ('Mitch Ryder')
, ('Modern English')
, ('Molkie Cole')
, ('Molly Hatchet')
, ('Monroes')
, ('Montrose')
, ('Motley Crue')
, ('Mott the Hoople')
, ('Mountain')
, ('Moxy')
, ('Mr. Big')
, ('Mungo Jerry')
, ('Nazareth')
, ('Neil Young')
, ('Nektar')
, ('Nickelback')
, ('Night Ranger')
, ('Nirvana')
, ('Norman Greenbaum')
, ('Nothing More')
, ('Oasis')
, ('Orleans')
, ('Otis Redding')
, ('Ozark Mountain Daredevils')
, ('Ozzy Osbourne')
, ('Pat Benatar')
, ('Pat Travers')
, ('Paul McCartney & Linda McCartney')
, ('Paul McCartney & Wings')
, ('Paul Simon')
, ('Pearl Jam')
, ('Pete Townshend')
, ('Peter Frampton')
, ('Peter Gabriel')
, ('Phil Collins')
, ('Pink Floyd')
, ('Poison')
, ('Procol Harum')
, ('Puddle of Mudd')
, ('Pure Prairie League')
, ('Queen')
, ('Queen / David Bowie')
, ('Queens of the Stone Age')
, ('Queensryche')
, ('Quicksilver Messenger Service')
, ('Quiet Riot')
, ('R.E.M.')
, ('Rainbow')
, ('Ram Jam')
, ('Ratt')
, ('Red Hot Chili Peppers')
, ('Red Rider')
, ('REO Speedwagon')
, ('Rick Derringer')
, ('Rick Springfield')
, ('Ringo Starr')
, ('Robert Palmer')
, ('Robert Plant')
, ('Robert Tepper')
, ('Robin Trower')
, ('Rockets')
, ('Rocky Burnette')
, ('Rod Stewart')
, ('Roger Daltry')
, ('Roger Hodgson')
, ('Rolling Stones')
, ('Rory Gallagher')
, ('Royal Bliss')
, ('Rush')
, ('Russ Ballard')
, ('Saga')
, ('Sam & Dave')
, ('Sammy Hagar')
, ('Santana')
, ('Scandal')
, ('School Of Fish')
, ('Scorpions')
, ('Seether')
, ('Sex Pistols')
, ('Sherbs')
, ('Shinedown')
, ('Simon & Garfunkel')
, ('Simple Minds')
, ('Skid Row')
, ('Slaughter')
, ('Smash Mouth')
, ('Smashing Pumpkins')
, ('Sniff ''n'' the Tears')
, ('Soft Cell')
, ('Soundgarden')
, ('Southside Johnny')
, ('Spencer Davis Group')
, ('Spin Doctors')
, ('Squeeze')
, ('Staind')
, ('Starset')
, ('Stealers Wheel')
, ('Steely Dan')
, ('Stephen Stills')
, ('Steppenwolf')
, ('Steve Earle')
, ('Steve Miller Band')
, ('Steve Perry')
, ('Steve Winwood')
, ('Steven Stills')
, ('Stevie Nicks')
, ('Stevie Nicks w/ Tom Petty and the Heartbreakers')
, ('Stevie Ray Vaughan')
, ('Stevie Wonder')
, ('Sting')
, ('Stone Temple Pilots')
, ('Stray Cats')
, ('Stryper')
, ('Stu Nunnery')
, ('Styx')
, ('Sublime')
, ('Sugar Ray')
, ('Sugarloaf')
, ('Supertramp')
, ('Survivor')
, ('Sweet')
, ('T. Rex')
, ('Talking Heads')
, ('Taxxi')
, ('Tears for Fears')
, ('Ted Nugent')
, ('Temple of the Dog')
, ('Ten Years After')
, ('Tesla')
, ('The Alan Parsons Project')
, ('The Alarm (IRS)')
, ('The Amboy Dukes')
, ('The Animals')
, ('The B-52''s')
, ('The Babys')
, ('The Band')
, ('The Beach Boys')
, ('The Beatles')
, ('The Black Crowes')
, ('The Black Keys')
, ('The Blues Brothers')
, ('The Byrds')
, ('The Cars')
, ('The Clash')
, ('The Cult')
, ('The Doobie Brothers')
, ('The Doors')
, ('The Fabulous Thunderbirds')
, ('The Firm')
, ('The Fixx')
, ('The Goo Goo Dolls')
, ('The James Gang')
, ('The Kings')
, ('The Kinks')
, ('The Knack')
, ('The Lemonheads')
, ('The Lovin'' Spoonful')
, ('The Mamas ')
, ('The Marshall Tucker Band')
, ('The Moody Blues')
, ('The New Eagles')
, ('The Offspring')
, ('The Outfield')
, ('The Outlaws')
, ('The Police')
, ('The Power Station')
, ('The Pretenders')
, ('The Ramones')
, ('The Romantics')
, ('The Small Faces')
, ('The Smithereens')
, ('The Spencer Davis Group')
, ('The Standells')
, ('The Traveling Wilburys')
, ('The Tubes')
, ('The Wallflowers')
, ('The White Stripes')
, ('The Who')
, ('The Youngbloods')
, ('Thin Lizzy')
, ('Third Eye Blind')
, ('Thunderclap Newman')
, ('Todd Rundgren')
, ('Tom Cochrane')
, ('Tom Petty & The Heartbreakers')
, ('Tommy Tutone')
, ('Tonic')
, ('Toto')
, ('Traffic')
, ('Trapeze')
, ('Triumph')
, ('Turtles')
, ('Twisted Sister')
, ('U2')
, ('UB40')
, ('UFO')
, ('Uriah Heep')
, ('Van Halen')
, ('Van Morrison')
, ('Violent Femmes')
, ('Vixen')
, ('War')
, ('Warrant')
, ('Warren Zevon')
, ('Weezer')
, ('Wet Willie')
, ('White Lion')
, ('Whitesnake')
, ('Why Not')
, ('Wild Cherry')
, ('Wildlife')
, ('Winger')
, ('Wishbone Ash')
, ('Y&T')
, ('Yes')
, ('Zebra')
, ('Zombies')
, ('ZZ Top')

  ) AS t (name)
)
,   bools AS (
  SELECT bool
  FROM   (VALUES
    (True)
  , (False)
  ) AS t (bool)
)
,   founded_years AS (
  SELECT generate_series(EXTRACT(YEAR FROM now()) - 50
                       , EXTRACT(YEAR FROM now())) AS founded_year
)
INSERT INTO artists (name, active, founded_year)
  SELECT  artist_names.name
         , bools.bool
         , founded_years.founded_year
  FROM    artist_names
        , bools
        , founded_years
  ORDER BY random()
  LIMIT 10;

-- Data for albums:
WITH album_names AS (
  SELECT name
  FROM (VALUES
  (NULL)
, ('Call of the Mastodon')
, ('Dimensions')
, ('Friend Or Foe')
, ('Muertos Vivos')
, ('Ordinary Day')
, ('Da Ghetto Psychic')
, ('Gin & Phonic')
, ('Pink World')
, ('Superinstrumental')
, ('I Need You')
, ('The Way Home')
, ('Placer & Castigo')
, ('Arrivederci')
, ('Dancing On The Ceiling')
, ('Outskirts')
, ('Cross Currents')
, ('Panjtan Ka Ghulam')
, ('Gold')
, ('Whatever Happened To Boredom?')
, ('1942-1952 Jimmy Wakely')
, ('All The Good Times')
, ('Un cafe_ setanta matins')
, ('Miss Machine')
, ('Sue Thompson - Her Very Best')
, ('Live')
, ('Strictly Confidential')
, ('The Real Twang Thang')
, ('Shake A Hand')
, ('Occasional Rain')
, ('The Emperor Falls')
, ('Best of The Shangri-Las')
, ('20 Of Her Best')
, ('Who Is Mike Jones?')
, ('Cracks')
, ('Pieces Of Time')
, ('The Palest Grey')
, ('A Match & Some Gasoline')
, ('Lo Mejor con La Orq. Broadway')
, ('Grown Man')
, ('A Bothered Mind')
, ('Greatest Hits')
, ('Etiquette')
, ('Ec8or')
, ('Too Much Too Soon')
, ('Bossa Nova Stories')
, ('Love_ Peace & Nappiness')
, ('Germicide')
, ('The Road To Hell Part 2')
, ('Vanguard Visionaries')
, ('Hometown 2001')
, ('Eat / Kiss: Music For The Films By Andy Warhol')
, ('The Ultimate Most Relaxing New Age Piano in the Universe')
, ('Classic Gold: Best of All')
, ('The Berzerker')
, ('Holy Roller Novocaine')
, ('White Trash ......')
, ('Murskapunkkia')
, ('The Man from Snowy River')
, ('One World One People')
, ('Tales Of Wonder')
, ('Waterbed Hev')
, ('The Best Of Both Worlds')
, ('Things Falling Apart')
, ('Your Funeral... My Trial (2009 Digital Remaster)')
, ('Oasis of Love')
, ('Yeah.  Well_ Anyway....')
, ('Un Titre de Toune')
, ('Live Inferno')
, ('Vendredi 13 - 1981')
, ('The Very Best Of')
, ('Country Lovers. Vol. 3')
, ('Affirmation')
, ('Lullabies To Paralyze')
, ('The Singles')
, ('What You Thought You Heard')
, ('15 Exitos Vol. 2 Flor Silvestre')
, ('Grim Prospects Remixes - Grim Prospects Will Never End')
, ('The Incredible Kai Winding Trombones')
, ('Staying on the Watch')
, ('Openbare Weg')
, ('Tip World Singles 2000')
, ('Praise Him...Live!')
, ('Spontanous Combustion')
, ('From All Sides')
, ('Maurice Chevalier  The Essential Collection Vol 1')
, ('Dave Pearce Best of the Dance Years 1988 - 1992')
, ('The Equinox')
, ('Feel Good All Over: Anthology 1970-1976')
, ('13th And Pine')
, ('Call Tyrone')
, ('Final Vinyl')
, ('Fifteen Poems By Dylan Thomas')
, ('The Early Tapes 1975-1976')
, ('Legacy')
, ('Louie Bluie Film Soundtrack')
, ('Donny Hathaway')
, ('Canciones De Amor De Miguel Gallardo')
, ('What up Detroit')
, ('Peterbilt Angel')
, ('Homemade Ice-Cream')
, ('White Feather')
, ('Can We Go Home Now')
, ('In North Carolina')
, ('Wintertime')
, ('Electropop')
, ('The Hit List')
, ('Underneath')
, ('99 Monkeys')
, ('Nothing Else Matters')
, ('A Tribute to The American Horse')
, ('Mis Momentos')
, ('Mish Mash_ Le Blues European: Musique Slave Et Klezmer')
, ('In this Life')
, ('Signify (Special Edition)')
, ('In Your Honor')
, ('Talk To Your Daughter')
, ('American Songbook - Bacharach')
, ('Scarcity')
, ('Fire')
, ('Hanging On (Premiere Performance Plus Track)')
, ('Grim Prospects Remixes - Prospects Are Getting Grimmer')
, ('Snowflakes')
, ('The Out Sound From Way In!')
, ('El Fuego De Dentro')
, ('No Control')
, ('Pentagrammaton')
, ('Pianissimo')
, ('Milan Milan')
, ('Auralux Reggae Showcase')
, ('Heaven')
, ('Up Above My Head')
, ('Pearl Jam')
, ('Take A Look')
, ('Crack The Skye')
, ('Behind The Blue')
, ('Matumago X Press')
, ('The Best of DJ Quik - Da Finale')
, ('LOOK (Original Motion Picture Soundtrack)')
, ('Relax')
, ('Joy In Our Hearts - The Gospel Side Of The Jordanaires')
, ('Enjoy!')
, ('A Nite On The Strip - Live')
, ('Boo-Tay')
, ('The Best Of Shelley Fabares [Digital Version]')
, ('In London_ In Love')
, ('Of My Times')
, ('Venus Envy')
, ('bFreddys Favorites: The Best of A Nightmare On Elm Street')
, ('Bitter Suites to Succubi')
, ('Manila Nights')
, ('Snapshot')
, ('End Of The Road - Single')
, ('7 Miles')
, ('Things Falling Apart')
, ('Leland Martin')
, ('For Screening Purposes Only')
, ('That Which Does Not Kill You...Can Only Make You Stronger : Three Way Split')
, ('Break The Night')
, ('Texas Songster')
, ('The Scott Wesley Brown Collection: A Library of 35 Favorite Songs')
, ('Time and Space')
, ('Death ... Is just the beginning Vol.4')
, ('Live In Tokyo')
, ('Dark Days In Paradise')
, ('Une petite pause')
, ('The B52s')
, ('Moments')
, ('Punk International')
, ('Forever')
, ('Breaks_ Beats & Blondes')
, ('Reiki - Spiritual Fitness_ Relaxation and Chakra Meditation')
, ('Peace At Last - EP')
, ('Alright_ Still (Deluxe)')
, ('Light Flight - The Anthology')
, ('This DJ')
, ('Miles To Miles')
, ('RoadKillOvercoat')
, ('Addressing The Nation With The Blues')
, ('Lagrimas Negras')
, ('Surprise')
, ('Apogee')
, ('Bone To Pick')
, ('Strictly Trucking')
, ('Music Of The Brazilian Masters')
, ('To Live Alone')
, ('PeeBoy EP')
, ('The Way West')
, ('Suburban')
, ('Hitzone 49')
, ('Time Will Tell')
, ('4 Day Tornado')
, ('Ao Vivo')
, ('The Altogether')
, ('Strength & Loyalty')
, ('Kivenkantaja')
, ('Live at the Grand Olympic Auditorium')
, ('Take One More Chance With Me')
, ('Revolutions Per Minute')
  ) AS t (name)
)
,    release_years AS (
  SELECT generate_series(EXTRACT(YEAR FROM now()) - 55
                       , EXTRACT(YEAR FROM now())) AS release_year
)
,    genres AS (
  SELECT genre
  FROM   (VALUES
    (NULL)
  , ('Pop')
  , ('Rock')
  , ('Classic')
  , ('Oldies')
  , ('Jazz')
  , ('R&B')
  , ('Metal')
  ) AS t (genre)
)
,    availables AS (
  SELECT bool
  FROM   (VALUES
    (True)
  , (False)
  ) AS t (bool)
)
,    artist_ids AS (
  SELECT artist_id
        , founded_year
  FROM   artists
)
INSERT INTO albums (name, release_year, genre, available, artist_id)
  SELECT album_names.name
       , release_years.release_year
       , genres.genre
       , availables.bool
       , artist_ids.artist_id
  FROM album_names
     , release_years
     , genres
     , availables
     , artist_ids 
  WHERE release_years.release_year > artist_ids.founded_year
  ORDER BY random() 
  LIMIT 50;

-- Data for songs:
WITH positions AS (
  SELECT albums.album_id
          -- MAX songs per album:
        , generate_series(1, ROUND(random()::decimal * 20)) AS position
	        -- MAX length for song, MIN = 1 second
	      , ROUND(random()::decimal * 1000, 0) AS length
  FROM albums
)
INSERT INTO songs (album_id, position, length_sec)
  SELECT album_id
        , position
        , length
  FROM positions;

CREATE TABLE song_names (name TEXT);
INSERT INTO song_names VALUES
  ('Caught Up in You')
, ('Fantasy Girl')
, ('Hold On Loosely')
, ('Rockin'' Into the Night')
, ('Art For Arts Sake')
, ('Kryptonite')
, ('Loser')
, ('When I''m Gone')
, ('What''s Up?')
, ('Take On Me')
, ('Baby, Please Don''t Go')
, ('Back In Black')
, ('Big Gun')
, ('CAN''T STOP ROCK''N''ROLL')
, ('Dirty Deeds Done Dirt Cheap')
, ('For Those About To Rock')
, ('Girls Got Rhythm')
, ('Hard As A Rock')
, ('Have a Drink On Me')
, ('Hells Bells')
, ('Highway To Hell')
, ('It''s A Long Way To The Top')
, ('Jailbreak')
, ('Let There Be Rock')
, ('Let''s Get It Up')
, ('Live Wire')
, ('Moneytalks')
, ('Night Prowler')
, ('Rock and Roll Ain''t Noise Pollution')
, ('Shoot To Thrill')
, ('Shot Down In Flames')
, ('Sin City')
, ('T.N.T.')
, ('Thunderstruck')
, ('Touch Too Much')
, ('What Do You Do For Money Honey')
, ('Who Made Who')
, ('Whole Lotta Rosie')
, ('You Shook Me All Night Long')
, ('How Long')
, ('Dog On A Leash')
, ('Angel')
, ('Baby, Please Don''t Go')
, ('Back in the Saddle')
, ('Big Ten Inch')
, ('Come Together')
, ('Crazy')
, ('Cryin''')
, ('Draw The Line')
, ('Dream On')
, ('Dude (Looks Like a Lady)')
, ('Jaded')
, ('Janie''s Got A Gun')
, ('Kings and Queens')
, ('Last Child')
, ('Let the Music Do the Talking')
, ('Livin'' On The Edge')
, ('Love In An Elevator')
, ('Mama Kin')
, ('No More No More')
, ('One Way Street')
, ('Pink')
, ('Rag Doll')
, ('Same Old Song and Dance')
, ('Seasons of Wither')
, ('Sweet Emotion')
, ('The Other Side')
, ('Toys in the Attic')
, ('Train Kept A-Rollin''')
, ('Walk This Way')
, ('What It Takes')
, ('You See Me Crying')
, ('Hand In My Pocket')
, ('You Oughta Know')
, ('Black Velvet')
, ('Fantasy')
, ('BE MY LOVER')
, ('Billion Dollar Babies')
, ('Eighteen')
, ('Elected')
, ('House Of Fire')
, ('I''m Eighteen')
, ('No More Mr. Nice Guy')
, ('School''s Out')
, ('Under My Wheels')
, ('Welcome To My Nightmare')
, ('Down in a Hole')
, ('Man In The Box')
, ('No Excuses')
, ('Rooster')
, ('Them Bones')
, ('Would?')
, ('Ain''t Wastin'' Time No More')
, ('Blue Sky')
, ('Good Clean Fun')
, ('In Memory Of Elizabeth Reed')
, ('Jessica')
, ('Melissa')
, ('Midnight Rider')
, ('No One to Run With')
, ('One Way Out')
, ('Ramblin'' Man')
, ('Southbound')
, ('Statesboro Blues')
, ('Whippin'' Post')
, ('A Horse With No Name')
, ('Sister Golden Hair')
, ('Ventura Highway')
, ('Don''t Bring Me Down')
, ('Don''t Let Me Be Misunderstood')
, ('Immigrant Song')
, ('Roller')
, ('Hold Your Head Up')
, ('Coming into Los Angeles')
, ('Wayside')
, ('Heat of the Moment')
, ('Only Time Will Tell')
, ('So Into You')
, ('Spooky')
, ('Like a Stone')
, ('Blondes In Black Cars')
, ('Turn Up the Radio')
, ('Rock And Roll Party In The Streets')
, ('Let It Ride')
, ('Roll On Down The Highway')
, ('Takin'' Care Of Business')
, ('You Ain''t Seen Nothin'' Yet')
, ('Bad Company')
, ('Burnin'' Sky')
, ('Can''t Get Enough')
, ('Feel Like Makin'' Love')
, ('Gone Gone Gone')
, ('Good Lovin'' Gone Bad')
, ('Movin'' On')
, ('Ready For Love')
, ('Rock ''n'' Roll Fantasy')
, ('Rock Steady')
, ('Run With The Pack')
, ('Seagull')
, ('Shooting Star')
, ('Silver, Blue And Gold')
, ('When I See You Smile')
, ('No Matter What')
, ('Walks Like A Woman')
, ('(You Gotta) Fight for Your Right (To Party)')
, ('No Sleep Till Brooklyn')
, ('Loser')
, ('In a Big Country')
, ('Rock Around the Clock')
, ('AIN''T NO SUNSHINE')
, ('Cradle of Love')
, ('Dancing With Myself')
, ('Eyes Without a Face')
, ('Mony Mony')
, ('Rebel Yell')
, ('White Wedding')
, ('Allentown')
, ('Big Shot')
, ('Captain Jack')
, ('Don''t Ask Me Why')
, ('Goodnight Saigon')
, ('It''s Still Rock And Roll To Me')
, ('Miami 2017 {seen The Lights Go Out On Broadway} (live 1')
, ('Movin'' Out (Anthony''s Song)')
, ('My Life')
, ('New York State Of Mind')
, ('Only The Good Die Young')
, ('Piano Man')
, ('Prelude/angry Young Man')
, ('Scenes From An Italian Restaurant')
, ('SHE''S ALWAYS A WOMAN')
, ('Sometimes A Fantasy')
, ('The Ballad Of Billy The Kid')
, ('The Stranger')
, ('You May Be Right')
, ('Baby Come Back')
, ('Everybody Wants You')
, ('In the Dark')
, ('Lonely Is the Night')
, ('My Kinda Lover')
, ('Rock Me Tonight')
, ('She''s a Runner')
, ('The Stroke')
, ('Children Of The Sun')
, ('Fairies Wear Boots')
, ('Heaven and Hell')
, ('Iron Man')
, ('N.i.b.')
, ('Neon Knights')
, ('Paranoid')
, ('Sweet Leaf')
, ('The Wizard')
, ('War Pigs')
, ('Highway Song')
, ('Train, Train')
, ('Can''t Find My Way Home')
, ('Presence of the Lord')
, ('No Rain')
, ('Presence of the Lord')
, ('All the Small Things')
, ('Call Me')
, ('Heart of Glass')
, ('One Way Or Another')
, ('(Don''t Fear) The Reaper')
, ('Bucks Boogie')
, ('Burnin'' for You')
, ('Godzilla')
, ('I Love the Night')
, ('Summertime Blues')
, ('Song 2')
, ('Just Like A Woman')
, ('Knockin'' On Heaven''s Door')
, ('Like a Rolling Stone')
, ('Positively 4th Street')
, ('Subterranean Homesick Blues')
, ('Tangled Up In Blue')
, ('Exodus')
, ('Jamming')
, ('No Woman, No Cry')
, ('One Love')
, ('Stir It Up')
, ('Three Little Birds')
, ('Against The Wind')
, ('Betty Lou''s Gettin'' Out Tonigh')
, ('Come to Poppa')
, ('Feel Like a Number')
, ('Fire Down Below')
, ('Get Out of Denver')
, ('Her Strut')
, ('Hollywood Nights')
, ('Horizontal Bop')
, ('Katmandu')
, ('Mainstreet')
, ('Night Moves')
, ('Old Time Rock & Roll')
, ('Ramblin'' Gamblin'' Man')
, ('Rock And Roll Never Forgets')
, ('Roll Me Away')
, ('Still the Same')
, ('Sunspot Baby')
, ('The Fire Down Below')
, ('Travelin'' Man')
, ('Turn On Your Love Light')
, ('Turn The Page')
, ('We''ve Got Tonite')
, ('You''ll Accompany Me')
, ('Hypnotized')
, ('Bad Medicine')
, ('Blaze of Glory')
, ('Born To Be My Baby')
, ('Lay Your Hands On Me')
, ('Livin'' On A Prayer')
, ('Raise Your Hands')
, ('Runaway')
, ('She Don''t Know Me')
, ('Wanted Dead or Alive')
, ('You Give Love A Bad Name')
, ('Wait For You')
, ('Green Onions')
, ('A Man I''ll Never Be')
, ('Amanda')
, ('Cool The Engines')
, ('Don''t Look Back')
, ('Feelin'' Satisfied')
, ('Foreplay (Long Time)')
, ('Hitch A Ride')
, ('Let Me Take You Home Tonight')
, ('More Than a Feeling')
, ('Party')
, ('Peace of Mind')
, ('Rock & Roll Band')
, ('Smokin''')
, ('Something About You')
, ('The Journey/It''s Easy')
, ('Used To Bad News')
, ('We''re Ready')
, ('Lido Shuffle')
, ('Lowdown')
, ('Tarkio Road')
, ('The Way It Is')
, ('Atlantic City')
, ('Backstreets')
, ('Badlands')
, ('Blinded By the Light')
, ('Born In the U.S.A.')
, ('Born To Run')
, ('Cover Me')
, ('Dancing In the Dark')
, ('Glory Days')
, ('Growin'' Up')
, ('Hungry Heart')
, ('I''m On Fire')
, ('It''s Hard to Be a Saint in the City')
, ('Jersey Girl')
, ('Jungleland')
, ('Pink Cadillac')
, ('Prove It All Night')
, ('Racing in the Streets')
, ('Rosalita (Come Out Tonight)')
, ('She''s The One')
, ('Spirit In The Night')
, ('Tenth Avenue Freeze-Out')
, ('Thunder Road')
, ('Cuts Like a Knife')
, ('Heaven')
, ('Run to You')
, ('Somebody')
, ('Summer Of ''69')
, ('Sorry')
, ('For What It''s Worth')
, ('Mr. Soul')
, ('Rock & Roll Woman')
, ('Comedown')
, ('Machinehead')
, ('Far Behind')
, ('Goin'' up the Country')
, ('On the Road Again')
, ('IT''S TOO LATE')
, ('Oh Very Young')
, ('WILD WORLD')
, ('In America')
, ('Long Haired Country Boy')
, ('The Devil Went Down To Georgia')
, ('The Legend Of Wooley Swamp')
, ('The South''s Gonna Do It Again')
, ('Uneasy Rider')
, ('Ain''t That a Shame')
, ('Dream Police')
, ('I Want You to Want Me')
, ('She''s Tight')
, ('Surrender')
, ('Take Out The Gunman')
, ('25 Or 6 To 4')
, ('Beginnings')
, ('Feeling Stronger Every')
, ('I''m a Man')
, ('JUST YOU AND ME')
, ('Make Me Smile')
, ('Questions 67 and 68')
, ('Saturday In the Park')
, ('South California Purples')
, ('JOHNNY B. GOODE')
, ('Coming Home')
, ('Don''t Know What You Got')
, ('Gypsy Road')
, ('Nobody''s Fool')
, ('Somebody Save Me')
, ('Better Off Without You')
, ('Born Too Late')
, ('Cigarette')
, ('Hey You')
, ('Maybe')
, ('Penny On The Floor')
, ('The River')
, ('December')
, ('Shine')
, ('The World I Know')
, ('Hot Rod Lincoln')
, ('Monkey Bars')
, ('Mr. Jones')
, ('Low')
, ('Badge')
, ('Born Under A Bad Sign')
, ('Crossroads')
, ('I''m So Glad')
, ('Sunshine of Your Love')
, ('Tales Of Brave Ulysses')
, ('White Room')
, ('Higher')
, ('My Sacrifice')
, ('With Arms Wide Open')
, ('Bad Moon Rising')
, ('Born On the Bayou')
, ('Commotion')
, ('Down On the Corner')
, ('Fortunate Son')
, ('Green River')
, ('Have You Ever Seen the Rain?')
, ('I Heard It Through the Grapevine')
, ('Lodi')
, ('Lookin'' Out My Back Door')
, ('Proud Mary')
, ('Run Through the Jungle')
, ('Suzie Q')
, ('Sweet Hitch Hiker')
, ('The Midnight Special')
, ('Travelin'' Band')
, ('Up Around the Bend')
, ('Who''ll Stop the Rain')
, ('Fire Woman')
, ('Helplessly Hoping')
, ('Long Time Gone')
, ('Southern Cross')
, ('Suite: Judy Blue Eyes')
, ('Carry On')
, ('Ohio')
, ('Woodstock')
, ('(I Just) Died in Your Arms')
, ('High Enough')
, ('I HEAR YOU KNOCKING')
, ('Headkeeper')
, ('Only You Know And I Know')
, ('We Just Disagree')
, ('Welcome To The Boomtown')
, ('Changes')
, ('China Girl')
, ('Diamond Dogs')
, ('Fame')
, ('Fashion')
, ('Friday on My Mind')
, ('Golden Years')
, ('Heroes')
, ('Jean Genie')
, ('Let''s Dance')
, ('Modern Love')
, ('Panic in Detroit')
, ('Rebel Rebel')
, ('Space Oddity')
, ('Starman')
, ('Stay')
, ('Suffragette City')
, ('Young Americans')
, ('Ziggy Stardust')
, ('Rock On')
, ('There''s No Way Out Of Here')
, ('There''s No Way Out Of Here')
, ('Frenchette')
, ('California Girls')
, ('Just A Gigolo / I Ain''t Got Nobody')
, ('Yankee Rose')
, ('Burn')
, ('Child In Time')
, ('Highway Star')
, ('Hush')
, ('Kentucky Woman')
, ('Knocking At Your Backdoo')
, ('Lazy')
, ('Perfect Strangers')
, ('Smoke On The Water')
, ('Space Truckin''')
, ('Woman From Tokyo')
, ('Animal')
, ('Armageddon It')
, ('Bringin'' On The Heartbreak')
, ('Foolin''')
, ('Hysteria')
, ('Love Bites')
, ('On Through The Night')
, ('Photograph')
, ('Pour Some Sugar On Me')
, ('Rock of Ages')
, ('Rock Rock')
, ('Rocket')
, ('Too Late for Love')
, ('Enjoy the Silence')
, ('Bell Bottom Blues')
, ('Have You Ever Loved a Woman')
, ('Layla')
, ('Recognition')
, ('ANGELOS')
, ('Holy Diver')
, ('Rainbow In the Dark')
, ('The Last In Line')
, ('Brothers In Arms')
, ('Down To The Waterline')
, ('Expresso Love')
, ('Industrial Disease')
, ('Lady Writer')
, ('Money for Nothing')
, ('Romeo And Juliet')
, ('So Far Away')
, ('Solid Rock')
, ('Sultans of Swing')
, ('Walk of Life')
, ('Counting Blue Cars')
, ('Drift Away')
, ('Alone Again')
, ('In My Dreams')
, ('Into The Fire')
, ('Heavy Metal')
, ('All She Wants to Do Is Dance')
, ('Dirty Laundry')
, ('Sunset Grill')
, ('The Boys Of Summer')
, ('The Heart of the Matter')
, ('The Last Worthless Evening')
, ('American Pie')
, ('Ah! Leah!')
, ('Love Is Like A Rock')
, ('Season of the Witch')
, ('Sunshine Superman')
, ('COVER OF THE ROLLING STONE')
, ('Right Place Wrong Time')
, ('Anything, Anything')
, ('Hey, Hey (What Can I Do?)')
, ('Rio')
, ('Already Gone')
, ('Desperado')
, ('Heartache Tonight')
, ('Hotel California')
, ('I Can''t Tell You Why')
, ('In The City')
, ('Life in the Fast Lane')
, ('Lyin'' Eyes')
, ('New Kid In Town')
, ('One of These Nights')
, ('Peaceful Easy Feeling')
, ('Seven Bridges Road')
, ('Take It Easy')
, ('Take It to the Limit')
, ('Tequila Sunrise')
, ('The Best of My Love')
, ('The Long Run')
, ('Those Shoes')
, ('Victim of Love')
, ('Witchy Woman')
, ('Baby Hold On')
, ('Gimme Some Water')
, ('Shakin''')
, ('Take Me Home Tonight')
, ('Think I''m In Love')
, ('Two Tickets To Paradise')
, ('Frankenstein')
, ('Free Ride')
, ('WAR')
, ('CAN''T GET IT OUT OF MY HEAD')
, ('Do Ya')
, ('Don''t Bring Me Down')
, ('Evil Woman')
, ('Fire On High')
, ('Livin'' Thing')
, ('Roll Over Beethoven')
, ('Strange Magic')
, ('Sweet Talkin'' Woman')
, ('Telephone Line')
, ('Turn To Stone')
, ('All The Girls Love Alice')
, ('Bennie And The Jets')
, ('Candle in the Wind')
, ('Captain Fantastic')
, ('Crocodile Rock')
, ('DANIEL')
, ('Don''t Let The Sun Go Down On Me')
, ('Funeral for a Friend (Love Lies Bleeding)')
, ('Goodbye Yellow Brick Road')
, ('Harmony')
, ('Honky Cat')
, ('Levon')
, ('Madman Across The Water')
, ('Rocket Man')
, ('Saturday Night''s Alright for Fighting')
, ('Someone Saved My Life Tonight')
, ('Take Me to the Pilot')
, ('Teacher I Need You')
, ('THE BITCH IS BACK')
, ('Tiny Dancer')
, ('Where To Now St. Peter')
, ('Your Song')
, ('Fooled around and Fell in Love')
, ('Alison')
, ('Pump It Up')
, ('Veronica')
, ('From the Beginning')
, ('Hoedown')
, ('Karn Evil 9')
, ('Lucky Man')
, ('Still You Turn Me On')
, ('After Midnight')
, ('Bad Love')
, ('Call Me the Breeze')
, ('Cocaine')
, ('Don''t Think Twice, It''s Alright')
, ('Forever Man')
, ('I Can''t Stand It')
, ('I Shot The Sheriff')
, ('I''ve Got a Rock ''N'' Roll Heart')
, ('It''s In The Way That You Use It')
, ('Knockin'' On Heaven''s Door')
, ('Lay Down Sally')
, ('Layla')
, ('Let It Grow')
, ('Let It Rain')
, ('Pretending')
, ('She''s Waiting')
, ('Tears In Heaven')
, ('The Core')
, ('Willie and the Hand Jive')
, ('Wonderful Tonight')
, ('Cliffs Of Dover')
, ('The Final Countdown')
, ('Sweet Dreams (Are Made of This)')
, ('Inside Out')
, ('Santa Monica')
, ('The Boys Are Back In Town')
, ('What It''s Like')
, ('More Than Words')
, ('Mutha (Don''t Wanna Go To School Today)')
, ('Ooh La La')
, ('Stay With Me')
, ('Epic')
, ('House Of Pain')
, ('All The Kings Horses')
, ('Signs')
, ('Blue Letter')
, ('Don''t Stop')
, ('Dreams')
, ('Go Your Own Way')
, ('Gold Dust Woman')
, ('Gypsy')
, ('Hold Me')
, ('Hypnotized')
, ('I Don''t Want To Know')
, ('I''m So Afraid')
, ('Landslide')
, ('Little Lies')
, ('Monday Morning')
, ('Never Going Back Again')
, ('Oh Well')
, ('Rhiannon')
, ('Sara')
, ('Say You Love Me')
, ('Second Hand News')
, ('Sentimental Lady')
, ('The Chain')
, ('Tusk')
, ('World Turning')
, ('You Make Loving Fun')
, ('Hocus Pocus')
, ('Dreamer')
, ('Fool For The City')
, ('I Just Want To Make Love To You')
, ('Slow Ride')
, ('All My Life')
, ('Baker Street')
, ('Best of You')
, ('Everlong')
, ('Learn To Fly')
, ('Monkey Wrench')
, ('My Hero')
, ('The Pretender')
, ('These Days')
, ('Times Like These')
, ('Blue Morning, Blue Day')
, ('Cold As Ice')
, ('Dirty White Boy')
, ('Double Vision')
, ('Feels Like the First Time')
, ('Head Games')
, ('Hot Blooded')
, ('I Want to Know What Love Is')
, ('Juke Box Hero')
, ('Long, Long Way From Home')
, ('Love Has Taken Its Toll')
, ('Starrider')
, ('That Was Yesterday')
, ('Urgent')
, ('Waiting for a Girl Like You')
, ('Women')
, ('Joe''s Garage')
, ('Peaches En Regalia')
, ('All Right Now')
, ('Hemorrhage')
, ('Wishing Well')
, ('Maggot Brain')
, ('CARS')
, ('Dream Weaver')
, ('Love Is Alive')
, ('A Trick of the Tail')
, ('Abacab')
, ('Behind The Lines')
, ('Carpet Crawlers')
, ('Follow You Follow Me')
, ('Home by the Sea/Second Home by the Sea')
, ('Just A Job To Do')
, ('Land Of Confusion')
, ('Mama')
, ('Man On The Corner')
, ('Misunderstanding')
, ('No Reply At All')
, ('That''s All')
, ('The Lamb Lies Down On Broadway')
, ('Tonight Tonight (live)')
, ('Turn It On Again')
, ('Give Me Love')
, ('GOT MY MIND SET ON YOU')
, ('My Sweet Lord')
, ('Bad to the Bone')
, ('Delaware Slide')
, ('Get A Haircut')
, ('I Drink Alone')
, ('It Wasn''t Me')
, ('Move It On Over')
, ('One Bourbon, One Scotch, One Beer')
, ('Who Do You Love')
, ('Keep Your Hands To Yourself')
, ('Baker Street')
, ('Right Down the Line')
, ('Found Out About You')
, ('Hey Jealousy')
, ('Smuggler''s Blues')
, ('You Belong to the City')
, ('Marakesh Express')
, ('Are You Receiving Me')
, ('Radar Love')
, ('Twilight Zone')
, ('Sundown')
, ('Soulshine')
, ('Bad Time')
, ('Closer To Home (I''m Your Captain)')
, ('Loco-Motion')
, ('Shinin'' On')
, ('Some Kind of Wonderful')
, ('We''re an American Band')
, ('Alabama Getaway')
, ('Black-Throated Wind')
, ('Casey Jones')
, ('CHINA TOWN SHUFFLE ')
, ('Friend Of The Devil')
, ('Hell in a Bucket')
, ('Loser')
, ('Me and Bobby McGee')
, ('NOT FADEAWAY/GOING /AWAY')
, ('Scarlet Begonias')
, ('Shakedown Street')
, ('Sugar Magnolia')
, ('Touch of Grey')
, ('Truckin''')
, ('Turn On Your Lovelight')
, ('U.S. Blues')
, ('Uncle John''s Band')
, ('Mista Bone')
, ('Once Bitten, Twice Shy')
, ('Rock Me')
, ('Rollin'' Stoned')
, ('Save Your Love')
, ('Basket Case')
, ('Boulevard Of Broken Dreams')
, ('Brain Stew/Jaded')
, ('Good Riddance (Time Of Your Life)')
, ('Holiday (Live)')
, ('Holiday / Boulevard of Broken Dreams')
, ('Longview')
, ('When I Come Around')
, ('The Break Up Song')
, ('I''m No Angel')
, ('Midnight Rider')
, ('American Woman')
, ('Friends Of Mine')
, ('No Sugar Tonight / New Mother Nature')
, ('No Time')
, ('THESE EYES')
, ('Civil War')
, ('Don''t Cry')
, ('Knockin'' On Heaven''s Door')
, ('Live and Let Die')
, ('Mr. Brownstone')
, ('My Michelle')
, ('November Rain')
, ('Paradise City')
, ('Patience')
, ('Sweet Child O'' Mine')
, ('Used To Love Her')
, ('Welcome to the Jungle')
, ('You Could Be Mine')
, ('AS FAR AS YOU CAN SEE (AS MU')
, ('Axel F Theme')
, ('Cat''s In The Cradle')
, ('W*O*L*D*')
, ('Jump into the Fire')
, ('Never Been Any Reason')
, ('All I Wanna Do Is Make Love to You')
, ('Alone')
, ('Barracuda')
, ('Bebe le Strange')
, ('Crazy On You')
, ('Dog & Butterfly')
, ('Dreamboat Annie')
, ('Even It Up')
, ('Heartless')
, ('How Can I Refuse')
, ('If Looks Could Kill')
, ('Kick It Out')
, ('Little Queen')
, ('Love Alive')
, ('Magic Man')
, ('Mistral Wind')
, ('Never')
, ('Nothin'' at All')
, ('Rock And Roll')
, ('Stairway To Heaven')
, ('Straight On')
, ('Tell It Like It Is')
, ('What About Love?')
, ('Who Will You Run To')
, ('House Of Living')
, ('Sangre Por Sangre')
, ('Grey Ghost')
, ('Long Cool Woman')
, ('New Girl Now')
, ('ALL YOU ZOMBIES')
, ('AND WE DANCED')
, ('I Want A New Drug')
, ('30 Days In the Hole')
, ('Lust for Life')
, ('The Passenger')
, ('Radioactive')
, ('Devil Inside')
, ('Need You Tonight')
, ('New Sensation')
, ('What You Need')
, ('In A Gadda Da Vida')
, ('Flight Of Icarus')
, ('Run To The Hills')
, ('The Number Of The Beast')
, ('The Trooper')
, ('Wasted Years')
, ('Centerfold')
, ('Freeze-frame')
, ('Give It To Me')
, ('Houseparty')
, ('Looking For A Love')
, ('Love Stinks')
, ('Must of Got Lost')
, ('Night Time')
, ('Whammer Jammer')
, ('Boulevard')
, ('Doctor My Eyes')
, ('Load Out/Stay')
, ('Redneck Friend')
, ('Running On Empty')
, ('Somebody''s Baby')
, ('Take It Easy')
, ('The Load-out/stay')
, ('The Road and the Sky')
, ('Funk #49')
, ('Walk Away')
, ('YOU''VE GOT A FRIEND')
, ('Been Caught Stealing')
, ('Jane Says')
, ('Get It While You Can')
, ('Me and Bobby McGee')
, ('Move Over')
, ('Piece of My Heart')
, ('Summertime')
, ('Shakedown Cruise')
, ('Thunder Island')
, ('Freeway Jam')
, ('Rice Pudding')
, ('Somebody to Love')
, ('White Rabbit')
, ('Find Your Way Back')
, ('Jane')
, ('Ride the Tiger')
, ('We Built This City')
, ('Right Here Right Now')
, ('Are You Gonna Be My Girl')
, ('Cold Hard Bitch')
, ('Aqualung')
, ('Bungle In The Jungle')
, ('Cross-eyed Mary')
, ('Hymn 43')
, ('Living In The Past')
, ('Locomotive Breath')
, ('Nothing Is Easy')
, ('Teacher')
, ('Thick As A Brick')
, ('Too Old To Rock ''n'' Roll')
, ('TIME IN A BOTTLE')
, ('All Along the Watchtower')
, ('Angel')
, ('Are You Experienced?')
, ('Crosstown Traffic')
, ('Dolly Dagger')
, ('Fire')
, ('Foxey Lady')
, ('Hey Joe')
, ('If 6 Was 9')
, ('Like a Rolling Stone')
, ('Little Wing')
, ('Manic Depression')
, ('Purple Haze')
, ('Red House')
, ('Stone Free')
, ('The Wind Cries Mary')
, ('Third Stone From The Sun')
, ('Voodoo Child (Slight Return)')
, ('Margaritaville')
, ('Son of a Son of a Sailor')
, ('Why Don''t We Get Drunk')
, ('Bad Reputation')
, ('Crimson And Clover')
, ('I Hate Myself For Loving You')
, ('I Love Rock ''n Roll')
, ('Cry Me a River')
, ('Feelin'' Alright')
, ('The Letter')
, ('With A Little Help From My Friends')
, ('You Can Leave Your Hat On (Live)')
, ('Is She Really Going Out With Him?')
, ('Always With Me, Always With You')
, ('Summer Song')
, ('A Life Of Illusion')
, ('All Night Long')
, ('Analog Man')
, ('Funk #49')
, ('In the City')
, ('Life''s Been Good')
, ('Ordinary Average Guy')
, ('Rocky Mountain Way')
, ('The Confessor')
, ('Turn To Stone')
, ('On the Dark Side')
, ('Centerfield')
, ('The Old Man Down The Road')
, ('#9 Dream')
, ('Imagine')
, ('Instant Karma')
, ('Mind Games')
, ('Watching the Wheels')
, ('Woman')
, ('Again Tonight')
, ('Ain''t Even Done With the Night')
, ('Authority Song')
, ('Check It Out')
, ('Cherry Bomb')
, ('Crumblin'' Down')
, ('Hurts So Good')
, ('I Need A Lover')
, ('Jack & Diane')
, ('Lonely Ol'' Night')
, ('Paper in Fire')
, ('Pink Houses')
, ('R.O.C.K. In the U.S.A.')
, ('Rain On The Scarecrow')
, ('Small Town')
, ('What If I Came Knocking')
, ('Illegal Smile')
, ('I CAN SEE CLEARLY NOW')
, ('Brickyard Road')
, ('Shanty')
, ('Roadrunner')
, ('Any Way You Want It')
, ('City of the Angels')
, ('Don''t Stop Believin''')
, ('Escape')
, ('Faithfully')
, ('Feeling That Way')
, ('Just the Same Way')
, ('Lights')
, ('Look Into The Future')
, ('Lovin'', Touchin'' Squeezin''')
, ('Only the Young')
, ('Open Arms')
, ('Send Her My Love')
, ('Separate Ways (Worlds Apart)')
, ('Stone In Love')
, ('Wheel in the Sky')
, ('Who''s Crying Now')
, ('Breaking The Law')
, ('Diamonds And Rust')
, ('Electric Eye')
, ('Heading Out To The Highway')
, ('Hot Rockin''')
, ('Living After Midnight')
, ('The Ripper')
, ('Turbo Lover')
, ('You''ve Got Another Thing Comin''')
, ('Simple Man')
, ('Carry On Wayward Son')
, ('Dust In The Wind')
, ('Play the Game Tonight')
, ('Point of Know Return')
, ('I''m Alright')
, ('Just Dropped In')
, ('Blue On Black')
, ('Somehow, Somewhere, Someway')
, ('All Summer Long')
, ('Cowboy')
, ('Let''s Ride')
, ('If I Say')
, ('Sex On Fire')
, ('Use Somebody')
, ('Beth')
, ('Calling Dr. Love')
, ('Christeen Sixteen')
, ('Cold Gin')
, ('Detroit Rock City')
, ('Heaven''s On Fire')
, ('Lick It Up')
, ('Rock And Roll All Nite')
, ('Shout It out Loud')
, ('Strutter')
, ('Tears Are Falling')
, ('Long Stick Goes Boom')
, ('Screaming In The Night')
, ('Stayed Awake All Night')
, ('Sex Action')
, ('Key To The Rhyme')
, ('All My Love')
, ('Babe I''m Gonna Leave You')
, ('Black Dog')
, ('Black Mountain Side')
, ('Bonzo''s Montreaux')
, ('Boogie With Stu')
, ('Bring It On Home')
, ('Bron-y-aur Stomp')
, ('Celebration Day')
, ('Communication Breakdown')
, ('Custard Pie')
, ('D''Yer Mak''er')
, ('Dancing Days')
, ('Darlene')
, ('Dazed and Confused')
, ('Down By The Seaside')
, ('Fool In the Rain')
, ('For Your Life')
, ('Four Sticks')
, ('Friends')
, ('Gallows Pole')
, ('Going to California')
, ('Good Times Bad Times')
, ('Hats Off To {roy} Harper')
, ('Heartbreaker/living Loving Maid {she''s Just A Woman}')
, ('Hey Hey What Can I Do')
, ('Hot Dog')
, ('Houses of the Holy')
, ('How Many More Times')
, ('I Can''t Quit You Baby')
, ('Immigrant Song')
, ('In My Time of Dying')
, ('In the Evening')
, ('In the Light')
, ('Kashmir')
, ('Living Loving Maid (She''s Just a Woman)')
, ('Misty Mountain Hop')
, ('Moby Dick')
, ('NIGHT FLIGHT')
, ('No Quarter')
, ('Nobody''s Fault But Mine')
, ('Out On The Tiles')
, ('Over the Hills and Far Away')
, ('Ramble On')
, ('Rock and Roll')
, ('Royal Orleans')
, ('Since I''ve Been Loving You')
, ('South Bound Saurez')
, ('Stairway to Heaven')
, ('TANGERINE')
, ('Ten Years Gone')
, ('Thank You')
, ('That''s the Way')
, ('The Battle Of Evermore')
, ('The Crunge')
, ('The Lemon Song')
, ('The Ocean')
, ('The Rain Song')
, ('The Rover')
, ('The Song Remains the Same')
, ('THE WANTON SONG')
, ('Trampled Under Foot')
, ('Traveling Riverside Blues')
, ('What Is and What Should Never Be')
, ('When The Levee Breaks')
, ('Whole Lotta Love')
, ('You Shook Me')
, ('Your Time Is Gonna Come')
, ('Do You Know What I Mean')
, ('Woman')
, ('American Woman')
, ('Are You Gonna Go My Way')
, ('Fly Away')
, ('Stranger In A Strange Land')
, ('My Own Worst Enemy')
, ('Close My Eyes Forever')
, ('Kiss Me Deadly')
, ('All That You Dream')
, ('Dixie Chicken')
, ('I Alone')
, ('Lightning Crashes')
, ('Cult Of Personality')
, ('Bound for the Floor')
, ('Conquistador')
, ('Midnight Blue')
, ('Sweet Jane (Live)')
, ('Walk On The Wild Side')
, ('Lovin'' Every Minute of It')
, ('The Kid Is Hot Tonite')
, ('Turn Me Loose')
, ('Working for the Weekend')
, ('Wicked Sensation')
, ('Call Me the Breeze')
, ('Dixie/Sweet Home Alabama')
, ('Don''t Ask Me No Questions')
, ('Free Bird')
, ('Gimme Back My Bullets')
, ('Gimme Three Steps')
, ('I Know a Little')
, ('Saturday Night Special')
, ('Simple Man')
, ('Sweet Home Alabama')
, ('That Smell')
, ('The Ballad Of Curtis Loew')
, ('Tuesday''s Gone')
, ('What''s Your Name')
, ('You Got That Right')
, ('Merry-Go-Round')
, ('Blinded by the Light')
, ('Do Wah Diddy Diddy')
, ('Sex and Candy')
, ('Paradise By The Dashboard Light')
, ('TWO OUT OF THREE AIN''T BAD')
, ('You Took The Words Right Out Of My Mouth')
, ('I''m the Only One')
, ('Down Under')
, ('Who Can It Be Now?')
, ('Breadfan')
, ('Enter Sandman')
, ('Fade To Black')
, ('For Whom The Bell Tolls')
, ('Fuel')
, ('Harvester Of Sorrow')
, ('Hero of the Day')
, ('Lords of Summer (First Pass Version)')
, ('Master of Puppets')
, ('No Leaf Clover')
, ('Nothing Else Matters')
, ('One')
, ('Sad But True')
, ('Seek & Destroy')
, ('The Memory Remains')
, ('The Unforgiven')
, ('Turn The Page')
, ('Until It Sleeps')
, ('Wherever I May Roam')
, ('Whiskey In The Jar')
, ('Cruisin''')
, ('Drinkin'' in the Driveway')
, ('He Can''t Love You')
, ('Let''s Get the Show on the Road')
, ('My Town')
, ('Rosewood Bitters')
, ('Strike up the Band')
, ('Beds Are Burning')
, ('Devil With the Blue Dress On')
, ('I Melt With You')
, ('Sugar Boogie')
, ('Dreams I''ll Never See')
, ('Flirtin'' With Disaster')
, ('What Do All The People Know')
, ('Bad Motor Scooter')
, ('Rock Candy')
, ('Space Station #5')
, ('Don''t Go Away Mad (Just Go Away)')
, ('Dr. Feelgood')
, ('Girls, Girls, Girls')
, ('Home Sweet Home')
, ('Kickstart My Heart')
, ('Looks That Kill')
, ('Piece of Your Action')
, ('Same Ol'' Situation')
, ('Shout at the Devil')
, ('Smokin'' in the Boys Room')
, ('Wild Side')
, ('All the Young Dudes')
, ('Mississippi Queen')
, ('Moon Rider')
, ('Addicted To That Rush')
, ('In the Summertime')
, ('Hair Of The Dog')
, ('Love Hurts')
, ('Cinnamon Girl')
, ('Down by the River')
, ('Everybody Knows This Is Nowhere')
, ('Heart of Gold')
, ('Hey Hey, My My')
, ('Like a Hurricane')
, ('My My, Hey Hey')
, ('Old Man')
, ('Powderfinger')
, ('Rockin'' In the Free World')
, ('Southern Man')
, ('Sugar Mountain')
, ('The Needle and the Damage Done')
, ('When You Dance I Can Really Love')
, ('Show Me The Way')
, ('How You Remind Me')
, ('Photograph')
, ('Rockstar')
, ('Someday (Single Mix)')
, ('(You Can Still) Rock in America')
, ('Don''t Tell Me You Love Me')
, ('Rumors In The Air')
, ('Sister Christian')
, ('When You Close Your Eyes')
, ('About a Girl')
, ('All Apologies')
, ('Come As You Are')
, ('Dumb')
, ('In Bloom')
, ('Lithium')
, ('On a Plain')
, ('Polly')
, ('Smells Like Teen Spirit')
, ('The Man Who Sold the World')
, ('Spirit In The Sky')
, ('This Is The Time')
, ('Wonderwall')
, ('STILL THE ONE')
, ('(Sittin'' On) The Dock of the Bay')
, ('If You Wanna Get to Heaven')
, ('Jackie Blue')
, ('Bark At The Moon')
, ('Changes')
, ('Crazy Train')
, ('Diary Of A Madman')
, ('Flying High Again')
, ('Goodbye To Romance')
, ('I Don''t Know')
, ('Mama, I''m Coming Home')
, ('Mr. Crowley')
, ('Mr. Tinkertrain')
, ('No More Tears')
, ('Over the Mountain')
, ('Perry Mason')
, ('Purple Haze')
, ('Road To Nowhere')
, ('Rocky Mountain Way')
, ('See You on the Other Side')
, ('Shot in the Dark')
, ('Time After Time')
, ('Fire and Ice')
, ('Heartbreaker')
, ('Hell Is for Children')
, ('Hit Me With Your Best Shot')
, ('Invincible')
, ('Love Is A Battlefield')
, ('Shadows Of The Night')
, ('Treat Me Right')
, ('We Belong')
, ('You Better Run')
, ('Boom Boom/')
, ('Snortin Whiskey')
, ('The Back Seat Of My Car')
, ('Too Many People')
, ('Uncle Albert/Admiral Halsey')
, ('Another Day')
, ('Band on the Run')
, ('Birthday (Live)')
, ('Coming Up')
, ('Day Tripper')
, ('Helen Wheels')
, ('Hello Goodbye')
, ('Helter Skelter')
, ('Hey Jude (Live)')
, ('Hi Hi Hi')
, ('Jet')
, ('Junior''s Farm')
, ('Let ''Em In')
, ('Let Me Roll It')
, ('Listen To What The Man Says')
, ('Live and Let Die')
, ('Maybe I''m Amazed')
, ('My Love')
, ('Nineteen Hundred and Eighty Five')
, ('Silly Love Songs')
, ('Uncle Albert/Admiral Halsey')
, ('Venus and Mars/Rock Show')
, ('With a Little Luck')
, ('50 Ways to Leave Your Lover')
, ('Kodachrome')
, ('Loves Me Like a Rock')
, ('Me And Julio Down By The Schoolyard')
, ('You Can Call Me Al')
, ('Alive')
, ('Better Man')
, ('Black')
, ('Daughter')
, ('Dissident')
, ('Elderly Woman Behind the Counter in a Small Town')
, ('Even Flow')
, ('Jeremy')
, ('Last Kiss')
, ('Lightning Bolt')
, ('Not for You')
, ('Sirens')
, ('Yellow Ledbetter')
, ('GONNA GET YA')
, ('Let My Love Open the Door')
, ('Rough Boys')
, ('Baby, I Love Your Way')
, ('Do You Feel Like We Do')
, ('Show Me the Way')
, ('Something''s Happening/')
, ('Big Time')
, ('Games Without Frontiers')
, ('In Your Eyes')
, ('Red Rain')
, ('SHOCK THE MONKEY')
, ('Sledgehammer')
, ('Solsbury Hill')
, ('Don''t Lose My Number')
, ('I Don''t Care Anymore')
, ('In the Air Tonight')
, ('Another Brick In The Wall')
, ('Another Brick in the Wall, Pt. 2')
, ('Any Colour You Like')
, ('Arnold Layne')
, ('Astronomy Domine')
, ('Brain Damage')
, ('Brain Damage /Eclipse')
, ('Breathe')
, ('Careful With That Axe, Eugene')
, ('Comfortably Numb')
, ('Dogs')
, ('Empty Spaces')
, ('Empty Spaces/young Lust')
, ('Fearless')
, ('Goodbye Blue Sky')
, ('Have a Cigar')
, ('Hey You')
, ('Keep Talking')
, ('Learning to Fly')
, ('Money')
, ('Mother')
, ('On The Turning Away')
, ('One Of These Days')
, ('One Slip')
, ('Run Like Hell')
, ('See Emily Play')
, ('Set The Controls For The Heart Of The Sun')
, ('Shine On You Crazy Diamond')
, ('Speak to Me/Breathe')
, ('Take It Back')
, ('The Dogs Of War')
, ('The Great Gig In the Sky')
, ('The Happiest Days Of Our Lives/another Brick In The Wall')
, ('Time')
, ('Time/Gig in The Sky')
, ('Us and Them')
, ('Welcome To The Machine')
, ('Wish You Were Here')
, ('Young Lust')
, ('Every Rose Has Its Thorn')
, ('Look What The Cat Dragged In')
, ('Nothin'' But A Good Time')
, ('Something To Believe In')
, ('Talk Dirty To Me')
, ('A Salty Dog')
, ('A Whiter Shade of Pale')
, ('Blurry')
, ('Amie')
, ('Another One Bites the Dust')
, ('Bicycle Race')
, ('Bicycle Race/fat Bottomed Girls')
, ('Bohemian Rhapsody')
, ('Crazy Little Thing Called Love')
, ('Don''t Stop Me Now')
, ('Fat Bottomed Girls')
, ('It''s Late')
, ('Keep Yourself Alive')
, ('Killer Queen')
, ('One Vision')
, ('Somebody To Love')
, ('THESE ARE THE DAYS OF OUR LI')
, ('Tie Your Mother Down')
, ('Under Pressure')
, ('We Are the Champions')
, ('We Will Rock You')
, ('We Will Rock You/We Are The Champions')
, ('You''re My Best Friend')
, ('Under Pressure')
, ('No One Knows')
, ('Another Rainy Night')
, ('Eyes Of A Stranger')
, ('I Don''t Believe In Love')
, ('Jet City Woman')
, ('Silent Lucidity')
, ('Fresh Air')
, ('Pride of Man')
, ('Bang Your Head')
, ('Cum On Feel the Noize')
, ('Metal Health')
, ('It''s the End of the World As We Know It (And I Feel Fine)')
, ('Losing My Religion')
, ('Man On the Moon')
, ('Orange Crush')
, ('Stand')
, ('The One I Love')
, ('Man On The Silver Mountain')
, ('Since You Been Gone')
, ('Stone Cold')
, ('Street Of Dreams')
, ('Black Betty')
, ('Back for More')
, ('Round and Round')
, ('Way Cool Jr.')
, ('Breaking the Girl')
, ('By the Way')
, ('Californication')
, ('Dani California')
, ('Give It Away')
, ('Scar Tissue')
, ('Soul to Squeeze')
, ('Under the Bridge')
, ('Lunatic Fringe')
, ('Back On The Road Again')
, ('Don''t Let Him Go')
, ('Golden Country')
, ('I Can''t Fight This Feeling')
, ('Keep On Loving You')
, ('Keep Pushin''  1977')
, ('Like You Do')
, ('Ridin'' the Storm Out')
, ('Roll With the Changes')
, ('Take It on the Run')
, ('Time For Me To Fly')
, ('Rock And Roll, Hoochie Koo')
, ('Jessie''s Girl')
, ('Back Off Boogaloo')
, ('Early 1970 [*]')
, ('It Don''t Come Easy')
, ('No No Song')
, ('Photograph')
, ('Your''re Sixteen')
, ('Addicted to Love')
, ('Bad Case Of Lovin'' You')
, ('Simply Irresistible')
, ('Big Log')
, ('In The Mood')
, ('Little By Little')
, ('No Easy Way Out')
, ('Bridge of Sighs')
, ('Little Bit of Sympathy')
, ('Too Rolling Stoned')
, ('Oh, Well')
, ('Tired Of Toein'' The Line')
, ('Every Picture Tells A Story')
, ('Hot Legs')
, ('I Know I''m Losing You')
, ('Maggie May')
, ('Reason to Believe')
, ('Stay with Me')
, ('The First Cut Is The Deepest')
, ('Tonight''s the Night (Gonna Be Alright)')
, ('You Wear It Well')
, ('You''re In My Heart (The Final Acclaim)')
, ('Free Me')
, ('Had a Dream (Sleeping With the Enemy)')
, ('The Logical Song')
, ('(I Can''t Get No) Satisfaction')
, ('19th Nervous Breakdown')
, ('Ain''t Too Proud to Beg')
, ('Almost Hear You Sigh')
, ('Angie')
, ('Beast Of Burden')
, ('Bitch')
, ('Brown Sugar')
, ('Can''t You Hear Me Knocking')
, ('CAROL')
, ('Da Da Doo Ron Ron')
, ('Dance Little Sister')
, ('Doo Doo Doo Doo Doo (Heartbreaker)')
, ('Doom And Gloom')
, ('Emotional Rescue')
, ('Fortune Teller')
, ('Get Off My Cloud')
, ('Get Off Of My Cloud')
, ('Gimme Shelter')
, ('Hand of Fate')
, ('Hang Fire')
, ('Happy')
, ('Heartbreaker')
, ('Honky Tonk Women')
, ('IT''S ALL OVER NOW')
, ('It''s Only Rock ''n Roll')
, ('Jumpin'' Jack Flash')
, ('Just My Imagination')
, ('Let It Bleed')
, ('Let''s Spend the Night Together')
, ('Like A Rolling Stone')
, ('Little Queenie')
, ('Midnight Rambler')
, ('Miss You')
, ('Monkey Man')
, ('Mother''s Little Helper')
, ('Paint It Black')
, ('Shattered')
, ('She''s a Rainbow')
, ('She''s So Cold')
, ('Start Me Up')
, ('Street Fighting Man')
, ('Sympathy For The Devil')
, ('THE LAST TIME')
, ('THE SPIDER AND THE FLY')
, ('TIME IS ON MY SIDE')
, ('Time Waits for No One')
, ('Tumbling Dice')
, ('Under My Thumb')
, ('UNDERCOVER OF THE NIGHT')
, ('Waiting on a Friend')
, ('Wild Horses')
, ('You Can''t Always Get What You Want')
, ('YOU GOT THE SILVER')
, ('YOU GOTTA MOVE')
, ('Bullfrog Blues')
, ('Cry Sister')
, ('2112: Overture / The Temples of Syrinx (Chronicles Version)')
, ('Closer to the Heart')
, ('Entre Nous')
, ('Finding My Way')
, ('Fly By Night')
, ('Freewill')
, ('In The Mood')
, ('Limelight')
, ('New World Man')
, ('Red Barchetta')
, ('Show Don''t Tell')
, ('Subdivisions')
, ('Summertime Blues')
, ('Test For Echo')
, ('The Spirit of Radio')
, ('The Trees')
, ('Time Stand Still (live)')
, ('Tom Sawyer')
, ('Working Man')
, ('YYZ')
, ('Voices')
, ('On The Loose')
, ('SOUL MAN')
, ('Can''t Get Loose')
, ('Heavy Metal')
, ('I Can''t Drive 55')
, ('I''ll Fall In Love Again')
, ('Plain Jane')
, ('Red')
, ('There''s Only One Way to Rock')
, ('Three Lock Box')
, ('Trans Am (Highway Wonderland)')
, ('Turn Up The Music  1977')
, ('Black Magic Woman')
, ('Europa')
, ('Evil Ways')
, ('Jingo')
, ('No One to Depend On')
, ('Oye Como Va')
, ('Put Your Lights On (feat. Everlast)')
, ('Smooth')
, ('Soul Sacrifice')
, ('Well All Right')
, ('Winning')
, ('The Warrior')
, ('3 Strange Days')
, ('Big City Nights')
, ('Blackout')
, ('Don''t Believe Her')
, ('Holiday')
, ('Loving You Sunday Morning')
, ('No One Like You')
, ('Rock You Like a Hurricane')
, ('Still Loving You')
, ('The Zoo')
, ('Wind Of Change')
, ('Remedy')
, ('Words As Weapons')
, ('God Save The Queen')
, ('No Turning Back')
, ('45')
, ('America')
, ('Cecilia')
, ('Mrs. Robinson')
, ('The Sounds Of Silence')
, ('Don''t You')
, ('18 And Life')
, ('I Remember You')
, ('Youth Gone Wild')
, ('Fly To The Angels')
, ('All Star')
, ('1979')
, ('Bullet With Butterfly Wings')
, ('Landslide')
, ('Today')
, ('Driver''s Seat')
, ('Tainted Love')
, ('Black Hole Sun')
, ('Burden in My Hand')
, ('Fell On Black Days')
, ('Spoonman')
, ('Havin'' A Party')
, ('The Fever')
, ('GIMME SOME LOVIN''')
, ('Two Princes')
, ('Black Coffee In Bed')
, ('Pulling Mussels')
, ('Tempted')
, ('It''s Been Awhile')
, ('My Demons')
, ('Stuck In the Middle With You')
, ('Black Cow')
, ('Deacon Blues')
, ('Dirty Work')
, ('Do It Again')
, ('Fm {no Static At All}')
, ('Hey Nineteen')
, ('Peg')
, ('Reelin'' in the Years')
, ('Rikki Don''t Lose That Number')
, ('Love the One You''re With')
, ('Treetop Flyer')
, ('Born to Be Wild')
, ('Magic Carpet Ride')
, ('Copperhead Road')
, ('Abracadabra')
, ('Fly Like an Eagle')
, ('Jet Airliner')
, ('Jungle Love')
, ('Living in the U.S.A.')
, ('Mercury Blues')
, ('Rock ''N Me')
, ('Space Cowboy')
, ('Swingtown')
, ('Take the Money and Run')
, ('The Joker')
, ('The Stake')
, ('Threshold/Jet Airliner')
, ('True Fine Love')
, ('Your Cash Ain''t Nothin But Trash')
, ('Oh Sherrie')
, ('Back In the High Life Again')
, ('Higher Love')
, ('Roll With It')
, ('While You See a Chance')
, ('Love The One You''Re With')
, ('Edge of Seventeen')
, ('Leather and Lace')
, ('Stand Back')
, ('Stop Draggin'' My Heart Around')
, ('Stop Draggin'' My Heart Around')
, ('Cold Shot')
, ('Couldn''t Stand the Weather')
, ('Crossfire')
, ('Life by the Drop')
, ('Little Wing')
, ('Look At Little Sister')
, ('Pride And Joy')
, ('Scuttle Buttin''')
, ('Superstition [Live]')
, ('Taxman')
, ('Texas Flood')
, ('The House Is Rockin''')
, ('The Sky Is Crying')
, ('Tightrope')
, ('Voodoo Chile {slight Return}')
, ('Superstition')
, ('Fortress Around Your Heart')
, ('If You Love Somebody Set Them Free')
, ('Big Empty')
, ('Creep')
, ('Interstate Love Song')
, ('Lady Picture Show')
, ('Plush')
, ('Sex Type Thing')
, ('Trippin'' on a Hole in a Paper Heart')
, ('Vasoline')
, ('Rock This Town')
, ('Stray Cat Strut')
, ('To Hell With the Devil')
, ('The Isle Of Debris')
, ('Blue Collar Man')
, ('Come Sail Away')
, ('Crystal Ball')
, ('Fooling Yourself')
, ('Lady')
, ('Light Up')
, ('Lorelei')
, ('Renegade')
, ('Suite Madame Blue')
, ('The Grand Illusion')
, ('Too Much Time On My Hands')
, ('What I Got')
, ('Wrong Way')
, ('Fly')
, ('Green Eyed Lady')
, ('Bloody Well Right')
, ('Breakfast in America')
, ('Dreamer')
, ('Give a Little Bit')
, ('Goodbye Stranger')
, ('Take the Long Way Home')
, ('The Logical Song')
, ('Eye of the Tiger')
, ('I Can''t Hold Back')
, ('Ballroom Blitz')
, ('Fox On The Run')
, ('Love Is Like Oxygen')
, ('Bang a Gong (Get It On)')
, ('Jeepster')
, ('And She Was')
, ('Burning Down the House')
, ('Life During Wartime')
, ('Once In A Lifetime')
, ('Psycho Killer')
, ('Road To Nowhere')
, ('Stay Up Late')
, ('Take Me To The River')
, ('Wild Wild Life')
, ('I''m Leaving')
, ('Everybody Wants to Rule the World')
, ('Head Over Heels')
, ('Shout')
, ('Cat Scratch Fever')
, ('Dog Eat Dog')
, ('Free for All')
, ('Great White Buffalo')
, ('Stranglehold')
, ('Wango Tango')
, ('Hunger Strike')
, ('I''d Love To Change The World')
, ('I''m Goin'' Home')
, ('Little Suzi')
, ('Love Song')
, ('Modern Day Cowboy')
, ('Signs')
, ('Breakdown')
, ('Eye In the Sky')
, ('Games People Play')
, ('I Wouldn''t Want to Be Like You')
, ('Rain In the Summertime')
, ('Journey to the Center of the Mind')
, ('Don''t Bring Me Down')
, ('House Of The Rising Sun')
, ('Monterey')
, ('San Franciscan Nights')
, ('Spill the Wine')
, ('Love Shack')
, ('Roam')
, ('Back On My Feet Again')
, ('Isn''t It Time')
, ('Chest Fever')
, ('The Night They Drove Old Dixie Down')
, ('The Weight')
, ('Up On Cripple Creek')
, ('Good Vibrations')
, ('A Day In The Life')
, ('A Hard Day''s Night')
, ('A Saturday Club Xmas/Crimble Medley')
, ('Across The Universe')
, ('All My Loving')
, ('All You Need Is Love')
, ('And Your Bird Can Sing')
, ('ANYTIME AT ALL')
, ('Baby You''re A Rich Man')
, ('Back In the U.S.S.R.')
, ('BAD BOY')
, ('BALLAD OF JOHN AND YOKO')
, ('Birthday')
, ('Blackbird')
, ('Can''t Buy Me Love')
, ('Come Together')
, ('Cry For A Shadow')
, ('Day Tripper')
, ('Dear Prudence')
, ('Don''t Let Me Down')
, ('Drive My Car')
, ('Eight Days A Week')
, ('Eleanor Rigby')
, ('Everybody''s Got Something To Hide Except Me And My Monk')
, ('Fixing A Hole')
, ('From Me To You')
, ('Get Back')
, ('Getting Better')
, ('GIRL')
, ('Golden Slumbers')
, ('Good Day Sunshine')
, ('Got To Get You Into My Life')
, ('Hello Goodbye')
, ('Help!')
, ('Helter Skelter')
, ('Here Comes The Sun')
, ('Hey Jude')
, ('I Am the Walrus')
, ('I Feel Fine')
, ('I Saw Her Standing There')
, ('I Want To Hold Your Hand')
, ('I Want You (She''s So Heavy)')
, ('I''ll Follow The Sun')
, ('I''m A Loser')
, ('I''m Down')
, ('I''ve Got A Feeling')
, ('I''ve Just Seen A Face')
, ('IN MY LIFE')
, ('IT WON''T BE LONG')
, ('Lady Madonna')
, ('Let It Be')
, ('LITTLE CHILD')
, ('Love Me Do')
, ('Lovely Rita')
, ('Lucy In The Sky With Diamonds')
, ('Magical Mystery Tour')
, ('Maxwell''s Silver Hammer')
, ('Norwegian Wood')
, ('NOWHERE MAN')
, ('Ob-la-di, Ob-la-da')
, ('OH DARLING')
, ('P.s. I Love You')
, ('Paperback Writer')
, ('Penny Lane')
, ('Please Please Me')
, ('Reprise / Day in the Life')
, ('Revolution')
, ('ROCK AND ROLL MUSIC')
, ('Rocky Raccoon')
, ('Roll Over Beethoven')
, ('Sgt. Pepper Inner Groove')
, ('Sgt. Pepper''s Lonely Hearts Club Band')
, ('Sgt. Pepper''s Lonely Hearts Club Band (Reprise)')
, ('Sgt. Pepper/a Day In The Life')
, ('Sgt. Pepper/with A Little Help From My Friends')
, ('She Loves You')
, ('SHE''S A WOMAN')
, ('She''s Leaving Home')
, ('Something')
, ('Strawberry Fields Forever')
, ('Sun King')
, ('The Ballad Of John And Yoko')
, ('THE CONTINUING STORY OF BUNG')
, ('The Fool On The Hill')
, ('The Long And Winding Road')
, ('The Word')
, ('Things We Said Today')
, ('Ticket to Ride')
, ('Twist and Shout')
, ('Two Of Us')
, ('We Can Work It Out')
, ('When I''m 64')
, ('While My Guitar Gently Weeps')
, ('Wild Honey Pie')
, ('With a Little Help From My Friends')
, ('Yellow Submarine')
, ('Yesterday')
, ('You Never Give Me Your Money')
, ('You''re Going To Lose That Girl')
, ('YOUR MOTHER SHOULD KNOW')
, ('A Conspiracy')
, ('Gone')
, ('Good Friday')
, ('Goodbye Daughters of the Revolution')
, ('Hard To Handle')
, ('Hotel Illness')
, ('Jealous Again')
, ('Kickin'' My Heart Around')
, ('Remedy')
, ('She Talks To Angels')
, ('Thorn In My Pride')
, ('Twice As Hard')
, ('Gold On The Ceiling')
, ('Lonely Boy')
, ('Soul Man')
, ('Eight Miles High')
, ('Bye Bye Love')
, ('Candy-o')
, ('Dangerious Type')
, ('Drive')
, ('Good Times Roll')
, ('Hello Again')
, ('It''s All I Can Do')
, ('Just What I Needed')
, ('Let''s Go')
, ('Magic')
, ('Moving In Stereo')
, ('My Best Friend''s Girl')
, ('Shake It Up')
, ('Since You''re Gone')
, ('Stereo/All Mixed Up')
, ('Tonight She Comes')
, ('You Might Think')
, ('You''re All I''ve Got Tonight')
, ('Clampdown')
, ('I Fought The Law')
, ('London Calling')
, ('Rock The Casbah')
, ('Should I Stay Or Should')
, ('Train In Vain')
, ('Fire Woman')
, ('Another Park, Another Sunday')
, ('Black Water')
, ('China Grove')
, ('It Keeps You Runnin''')
, ('Jesus Is Just Alright')
, ('Listen To The Music')
, ('Livin'' On the Fault Line')
, ('Long Train Runnin''')
, ('Natural Thing')
, ('Rockin'' Down The Highway')
, ('South City Midnight Lady')
, ('Take Me In Your Arms')
, ('Takin'' It To The Streets')
, ('UKIAH/THE CAPTAIN AND ME')
, ('What a Fool Believes')
, ('Wheels Of Fortune')
, ('Back Door Man')
, ('Break On Through')
, ('Five To One')
, ('Gloria')
, ('Hello, I Love You')
, ('L.A. Woman')
, ('Light My Fire')
, ('Love Her Madly')
, ('Love Me Two Times')
, ('Moonlight Drive')
, ('Peace Frog')
, ('People Are Strange')
, ('Riders On The Storm')
, ('Roadhouse Blues')
, ('Soul Kitchen')
, ('The Changeling')
, ('The Crystal Ship')
, ('Touch Me')
, ('Twentieth Century Fox')
, ('Waiting For The Sun')
, ('When the Music''s Over')
, ('Tuff Enuff')
, ('Radioactive')
, ('One Thing Leads To Another')
, ('Saved By Zero')
, ('Iris')
, ('Funk #49')
, ('This Beat Goes on/Switching to Glide')
, ('A Well Respected Man')
, ('All Day And All Of The Night')
, ('Apeman')
, ('Come Dancing')
, ('Destroyer')
, ('Lola')
, ('Sunny Afternoon')
, ('Superman')
, ('Tired of Waiting')
, ('Victoria')
, ('Waterloo Sunset')
, ('You Really Got Me')
, ('My Sharona')
, ('Mrs. Robinson')
, ('Summer In the City')
, ('CALIFORNIA DREAMIN''')
, ('Can''t You See')
, ('HEARD IT IN A LOVE SONG')
, ('Take The Highway')
, ('Gypsy')
, ('Question')
, ('Ride My See Saw')
, ('The Story In Your Eyes')
, ('Your Wildest Dreams')
, ('Life in the Fast Lane')
, ('Come Out and Play')
, ('Self Esteem')
, ('The Kids Aren''t Alright')
, ('Your Love')
, ('Green Grass & High Tides')
, ('Can''t Stand Losing You')
, ('De Do Do Do, De Da Da Da')
, ('Don''t Stand So Close To Me')
, ('Driven to Tears')
, ('Every Breath You Take')
, ('Every Little Thing She Does Is Magic')
, ('Invisible Sun')
, ('King Of Pain')
, ('Message In A Bottle')
, ('Roxanne')
, ('So Lonely')
, ('Spirits In The Material World')
, ('Synchronicity II')
, ('Walking On The Moon')
, ('Wrapped Around Your Finger')
, ('Some Like It Hot')
, ('Back On The Chain Gang')
, ('Brass In Pocket')
, ('Don''t Get Me Wrong')
, ('Message of Love')
, ('Middle Of The Road')
, ('My City Was Gone')
, ('Mystery Achievement')
, ('TALK OF THE TOWN')
, ('Blitzkrieg Bop')
, ('Do You Remember Rock ''n'' Roll Radio')
, ('I Wanna Be Sedated')
, ('Rock ''n'' Roll High School')
, ('Rockaway Beach')
, ('Teenage Lobotomy')
, ('TALKING IN YOUR SLEEP')
, ('What I Like About You')
, ('Itchycoo Park')
, ('A Girl Like You')
, ('I''m A Man')
, ('Dirty Water')
, ('End of the Line')
, ('Handle with Care')
, ('Tweeter and the Monkey Man')
, ('She''s a Beauty')
, ('Talk To Ya Later')
, ('One Headlight')
, ('Seven Nation Army')
, ('5:15')
, ('ANOTHER TRICKY DAY')
, ('Athena')
, ('Baba O''Reilly')
, ('Bargain')
, ('Behind Blue Eyes')
, ('Eminence Front')
, ('Getting In Tune')
, ('Going Mobile')
, ('Happy Jack')
, ('I Can See For Miles')
, ('I CAN''T EXPLAIN')
, ('I''m Free')
, ('Join Together')
, ('Long Live Rock')
, ('Love Reign O''er Me')
, ('Magic Bus')
, ('My Generation')
, ('Pinball Wizard')
, ('Shakin'' All Over')
, ('Squeeze Box')
, ('Substitute')
, ('Summertime Blues')
, ('The Kids Are Alright')
, ('The Real Me')
, ('THE SEEKER')
, ('THE SONG IS OVER')
, ('We''re Not Gonna Take It')
, ('Who Are You')
, ('Won''t Get Fooled Again')
, ('You Better You Bet')
, ('Get Together')
, ('Jailbreak')
, ('The Boys Are Back In Town')
, ('The Cowboy Song')
, ('Semi-Charmed Life')
, ('Something In the Air')
, ('Bang the Drum All Day')
, ('Hello It''s Me')
, ('I Saw the Light')
, ('We Gotta Get You a Woman')
, ('Life Is a Highway')
, ('A Face In The Crowd')
, ('A Woman In Love')
, ('American Dream Plan B')
, ('American Girl')
, ('Breakdown')
, ('Change of Heart')
, ('Don''t Come Around Here No More')
, ('Don''t Do Me Like That')
, ('Even the Losers')
, ('Fooled Again (I Don''t Like It)')
, ('Free Fallin''')
, ('Here Comes My Girl')
, ('I Need to Know')
, ('I Won''t Back Down')
, ('Into the Great Wide Open')
, ('Jammin'' Me')
, ('Learning To Fly')
, ('Listen To Your Heart')
, ('Mary Jane''s Last Dance')
, ('Refugee')
, ('Runnin'' Down a Dream')
, ('Stop Draggin'' My Heart Around')
, ('The Waiting')
, ('U Get Me High')
, ('Yer So Bad')
, ('You Don''t Know How It Feels')
, ('You Get Me High')
, ('You Got Lucky')
, ('You Wreck Me')
, ('867-5309 / Jenny')
, ('If You Could Only See')
, ('AFRICA')
, ('Hold The Line')
, ('Dear Mr. Fantasy')
, ('Empty Pages')
, ('Medicated Goo')
, ('Medusa')
, ('Fight The Good Fight')
, ('Hold On')
, ('I Can Survive')
, ('Lay It On the Line')
, ('Magic Power')
, ('Happy Together')
, ('I Wanna Rock')
, ('We''re Not Gonna Take It')
, ('Angel Of Harlem')
, ('Bad')
, ('Beautiful Day')
, ('Bullet the Blue Sky')
, ('Desire')
, ('Even Better Than the Real Thing')
, ('I Still Haven''t Found What I''m Looking For')
, ('I Will Follow')
, ('MLK/Pride')
, ('Mysterious Ways')
, ('New Year''s Day')
, ('One')
, ('Pride (In the Name of Love)')
, ('Sunday Bloody Sunday')
, ('Sweetest Thing')
, ('Vertigo')
, ('When Love Comes to Town')
, ('Where the Streets Have No Name')
, ('With Or Without You')
, ('Red Red Wine')
, ('Lights Out (Live)')
, ('Too Hot To Handle')
, ('Easy Livin''')
, ('Stealin''')
, ('The Wizard')
, ('(Oh) Pretty Woman')
, ('1984/jump')
, ('Ain''t Talkin'' ''bout Love')
, ('And the Cradle Will Rock...')
, ('Atomic Punk')
, ('Beautiful Girls')
, ('Best Of Both Worlds')
, ('Black And Blue')
, ('Dance the Night Away')
, ('Dancing In the Street')
, ('Dreams')
, ('Drop Dead Legs')
, ('Eruption - You Really Got Me')
, ('Everybody Wants Some!!')
, ('Feel Your Love Tonight')
, ('Feels So Good')
, ('Finish What Ya Started')
, ('Hot for Teacher')
, ('I''ll Wait')
, ('I''m the One')
, ('Ice Cream Man')
, ('Intruder/ Pretty Woman')
, ('Jamie''s Cryin''')
, ('Jump')
, ('Little Dreamer')
, ('Little Guitars')
, ('Love Walks In')
, ('Mean Street')
, ('Panama')
, ('Poundcake')
, ('PRETTY WOMAN')
, ('Right Now')
, ('Runaround')
, ('Runnin'' with the Devil')
, ('Somebody Get Me A Doctor')
, ('Summer Nights')
, ('Take Your Whiskey Home')
, ('Top Jimmy')
, ('Top of the World')
, ('Unchained')
, ('When It''s Love')
, ('Where Have All the Good Times Gone!')
, ('Why Can''t This Be Love')
, ('You Really Got Me')
, ('And It Stoned Me')
, ('BLUE MONEY')
, ('Brown Eyed Girl')
, ('CRAZY LOVE')
, ('Domino')
, ('Gloria')
, ('Into The Mystic')
, ('Jackie Wilson Said')
, ('Moondance')
, ('Wild Night')
, ('Blister In the Sun')
, ('Edge of a Broken Heart')
, ('Low Rider')
, ('Spill the Wine')
, ('The Cisco Kid')
, ('Why Can''t We Be Friends')
, ('Cherry Pie')
, ('Uncle Tom''s Cabin')
, ('Lawyers, Guns and Money')
, ('Werewolves of London')
, ('Buddy Holly')
, ('Street Corner Serenade')
, ('Wait')
, ('Fool for Your Loving')
, ('Here I Go Again')
, ('Is This Love')
, ('Slide It In')
, ('Slow An'' Easy')
, ('Still of the Night')
, ('Who Are You?')
, ('PLAY THAT FUNKY MUSIC')
, ('Night Moves')
, ('We''ve Got Tonight')
, ('Can''t Get Enough')
, ('Headed For A Heartbreak')
, ('Seventeen')
, ('Persephone')
, ('Summertime Girls')
, ('Changes')
, ('I''ve Seen All Good People')
, ('It Can Happen')
, ('Leave It')
, ('Long Distance Runaround')
, ('Owner of a Lonely Heart')
, ('Roundabout')
, ('Starship Trooper')
, ('Wonderous Stories')
, ('Yours Is No Disgrace')
, ('Tell Me What You Want')
, ('Who''s Behind The Door')
, ('Time of the Season')
, ('A Fool for Your Stockings')
, ('Arrested For Driving While Blind')
, ('Beer Drinkers & Hell Raisers')
, ('Cheap Sunglasses')
, ('Gimme All Your Lovin')
, ('Got Me Under Pressure')
, ('Heard It On the X')
, ('I Thank You')
, ('I''m Bad, I''m Nationwide')
, ('Jesus Just Left Chicago')
, ('Just Got Paid')
, ('La Grange')
, ('Legs')
, ('My Head''s In Mississippi')
, ('Party On The Patio')
, ('Pearl Necklace')
, ('Sharp Dressed Man')
, ('She Loves My Automobile')
, ('Tube Snake Boogie')
, ('Tush')
, ('TV Dinners')
, ('WAITIN'' FOR THE BUS/JESUS JUST LEFT CHICAGO')
;

CREATE FUNCTION song_name_randomizer()
    RETURNS TEXT
    VOLATILE
    LANGUAGE SQL
  AS
  $$
    SELECT   name
	  FROM     song_names
	  ORDER BY random()
	  LIMIT    1;
  $$;
  
CREATE FUNCTION feat_artist_randomizer()
    RETURNS INTEGER
    VOLATILE
    LANGUAGE SQL
  AS
  $$
    SELECT   artist_id
	  FROM     artists
	  ORDER BY random()
	  LIMIT    1;
  $$;

UPDATE songs
SET    name = song_name_randomizer();

UPDATE songs
SET    artist_id = feat_artist_randomizer()
WHERE  song_id % ROUND((random()::decimal + 1) * 10)::integer = 2;

-- Clean up:
DROP TABLE song_names;
DROP FUNCTION song_name_randomizer();
DROP FUNCTION feat_artist_randomizer();

-- Data for order_lines:
WITH order_ids AS (
  SELECT order_id
  FROM   orders
)
,    album_ids AS (
  SELECT album_id
  FROM   albums
)
,    quantities AS (
  SELECT generate_series(1, 8) AS quantity
)
INSERT INTO order_lines (order_id, album_id, quantity)
  SELECT order_ids.order_id
       , album_ids.album_id
       , quantities.quantity
  FROM order_ids
     , album_ids
	 , quantities
  ORDER BY random()
  LIMIT 600
ON CONFLICT (order_id, album_id) DO NOTHING;







